version: "3.8"

services:
  postgres:
    image: bitnami/postgresql:latest
    restart: unless-stopped
    environment:
      POSTGRESQL_USERNAME: admin
      POSTGRESQL_PASSWORD: admin
      POSTGRESQL_DATABASE: root
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/bitnami/postgresql

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: unless-stopped
    ports:
      - "9001:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_REPLACE_SERVERS_ON_STARTUP: "True"
      PGADMIN_SERVER_JSON_FILE: /pgadmin4/servers.json
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    configs:
      - source: pgadmin_servers
        target: /pgadmin4/servers.json
        mode: 0444
      - source: pgadmin_pgpass
        target: /pgpass
        mode: 0600
    depends_on:
      - postgres

volumes:
  postgres_data:
  pgadmin_data:

configs:
  pgadmin_servers:
    file: ./servers.json
  pgadmin_pgpass:
    file: ./pgpass
