version: "3.8"

services:
  # PostgreSQL database server
  postgres:
    image: bitnami/postgresql:latest
    restart: unless-stopped
    environment:
      POSTGRESQL_USERNAME: admin
      POSTGRESQL_PASSWORD: admin
      POSTGRESQL_DATABASE: root
      POSTGRESQL_POSTGRES_PASSWORD: admin
      POSTGRESQL_ENABLE_REMOTE_CONNECTIONS: "yes"
    ports:
      - "5432:5432"
    volumes:
      - /home/kalpak44/postgres-data:/bitnami/postgresql

  # Web-based PostgreSQL administration UI
  pgadmin:
    image: dpage/pgadmin4:latest
    restart: unless-stopped
    ports:
      - "9001:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - /home/kalpak44/pgadmin-data:/var/lib/pgadmin
    depends_on:
      - postgres

  # Network-wide DNS ad and tracker blocking service
  adguardhome:
    image: adguard/adguardhome:latest
    container_name: adguardhome
    restart: always
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "8082:80/tcp"
    volumes:
      - /home/kalpak44/adguardhome/config:/opt/adguardhome/conf
      - /home/kalpak44/adguardhome/work:/opt/adguardhome/work
