version: "3.8"

services:
  postgres:
    image: bitnami/postgresql:latest
    restart: unless-stopped
    environment:
      POSTGRESQL_USERNAME: ${POSTGRES_USER}
      POSTGRESQL_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRESQL_DATABASE: ${POSTGRES_DB}
      POSTGRESQL_POSTGRES_PASSWORD: ${POSTGRES_SUPERUSER_PASSWORD}
      POSTGRESQL_ENABLE_REMOTE_CONNECTIONS: "yes"
    ports:
      - "5432:5432"
    volumes:
      - /home/kalpak44/postgres-data:/bitnami/postgresql

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: unless-stopped
    ports:
      - "9001:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - /home/kalpak44/pgadmin-data:/var/lib/pgadmin
    depends_on:
      - postgres

  adguardhome:
    image: adguard/adguardhome:latest
    container_name: adguardhome
    restart: always
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "8082:80/tcp"
    volumes:
      - /home/kalpak44/adguardhome/config:/opt/adguardhome/conf
      - /home/kalpak44/adguardhome/work:/opt/adguardhome/work

  vault:
    image: kalpak44/vault-docker-bootstrap:4a94336
    container_name: vault
    restart: unless-stopped
    cap_add:
      - IPC_LOCK
    ports:
      - "8200:8200"
      - "8201:8201"
    environment:
      # External reachable addresses (LAN)
      VAULT_API_ADDR: "http://192.168.1.50:8200"
      VAULT_CLUSTER_ADDR: "http://192.168.1.50:8201"

      # Enable KV v2 at secret/
      VAULT_ENABLE_KV: "true"
      VAULT_KV_PATH: "secret"

      # Write policies included in the image (admin + app-policy)
      VAULT_WRITE_POLICIES: "true"
      VAULT_ADMIN_POLICY_NAME: "admin"
      VAULT_APP_POLICY_NAME: "app-policy"

      # UI login (full admin, no warning)
      VAULT_ENABLE_USERPASS: "true"
      VAULT_UI_ADMIN_USERNAME: ${VAULT_UI_ADMIN_USERNAME}
      VAULT_UI_ADMIN_PASSWORD: ${VAULT_UI_ADMIN_PASSWORD}
      VAULT_UI_ADMIN_POLICIES: "admin"

      # Optional: AppRole for Kubernetes later (off for now)
      VAULT_ENABLE_APPROLE: "false"
      # VAULT_ENABLE_APPROLE: "true"
      # VAULT_APPROLE_NAME: "k8s-app"
      # VAULT_APPROLE_POLICIES: "app-policy"

    volumes:
      - /home/kalpak44/vault/data:/vault/data
      - /home/kalpak44/vault/file:/vault/file
