version: "3.8"

services:
  postgres:
    image: bitnami/postgresql:latest
    restart: unless-stopped
    environment:
      POSTGRESQL_USERNAME: admin
      POSTGRESQL_PASSWORD: admin
      POSTGRESQL_DATABASE: root
      POSTGRESQL_POSTGRES_PASSWORD: admin
      POSTGRESQL_ENABLE_REMOTE_CONNECTIONS: "yes"
    ports:
      - "5432:5432"
    volumes:
      - /home/kalpak44/postgres-data:/bitnami/postgresql

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: unless-stopped
    ports:
      - "9001:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - /home/kalpak44/pgadmin-data:/var/lib/pgadmin
    depends_on:
      - postgres
