version: "3.8"

services:
  postgres:
    image: bitnami/postgresql:latest
    restart: unless-stopped
    environment:
      # Your "admin" user for normal work:
      POSTGRESQL_USERNAME: ${POSTGRES_USER}
      POSTGRESQL_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRESQL_DATABASE: ${POSTGRES_DB}

      # The real postgres superuser password:
      POSTGRESQL_POSTGRES_PASSWORD: ${POSTGRES_SUPERUSER_PASSWORD}

      POSTGRESQL_ENABLE_REMOTE_CONNECTIONS: "yes"
    ports:
      - "5432:5432"
    volumes:
      - /home/kalpak44/postgres-data:/bitnami/postgresql

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: unless-stopped
    ports:
      - "9001:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - /home/kalpak44/pgadmin-data:/var/lib/pgadmin
    depends_on:
      - postgres

  adguardhome:
    image: adguard/adguardhome:latest
    container_name: adguardhome
    restart: always
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "8082:80/tcp"
    volumes:
      - /home/kalpak44/adguardhome/config:/opt/adguardhome/conf
      - /home/kalpak44/adguardhome/work:/opt/adguardhome/work
